/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "linkedlist.h"

node *
addlink_1_svc(lists *argp, struct svc_req *rqstp)
{
	printf("Welcome to remote Function\n");
	node *temp,*temp2;
	temp=argp->l1;
	temp2=argp->l1;
	while(argp->l1!=NULL)
	{
		//printf("Data of l1= %d\n ",argp->l1->data);
		//printf("Data of l2 = %d\n ",argp->l2->data);
		argp->l1->data=argp->l1->data+argp->l2->data;
		argp->l1 = argp->l1->next;
		argp->l2 = argp->l2->next;
		
	}
//	result =(char*)temp;
	while(temp2!=NULL)
	{
		//printf("temp2->data%d\n = ",temp2->data);
		temp2=temp2->next;
	}
	return temp ;
}
