/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "array.h"

bool_t
xdr_Array (XDR *xdrs, Array *objp)
{
	/*register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->a, sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;*/
	
	return xdr_array(
					xdrs,
					(char**) (&(objp->a)),
					&(objp->size),
					200,
					sizeof(int),
					(xdrproc_t)xdr_int);
	
	
}
