/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "array.h"


void
array_prog_1(char *host,Array sum_1_arg)
{
	CLIENT *clnt;
	int  *result_1;
	

#ifndef	DEBUG
	clnt = clnt_create (host, ARRAY_PROG, ARRAY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int i;
	for(i=0;i<sum_1_arg.size;i++)
	{
		
		printf("sum_1_arg.a[i] = %d\n ",sum_1_arg.a[i]);
	}
	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Result :%d\n ",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int n=atoi((argv[2])),i;
	Array temp;
	temp.size=n;
	printf("temp.size = %d\n ",temp.size);
	temp.a =(int*)malloc(sizeof(int)*n);
	for(i=0;i<n;i++)
	{
		
		temp.a[i]=atoi(argv[3+i]);
		printf("temp.a[i] = %d\n ",temp.a[i]);
	}
	 
	array_prog_1 (host,temp);
exit (0);
}
