/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LINKEDLIST_H_RPCGEN
#define _LINKEDLIST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct node {
	int data;
	struct node *next;
};
typedef struct node node;

struct lists {
	node *l1;
	node *l2;
};
typedef struct lists lists;

#define LINKEDLIST_PROG 0x23451111
#define LINKEDLIST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define addlink 1
extern  node * addlink_1(lists *, CLIENT *);
extern  node * addlink_1_svc(lists *, struct svc_req *);
extern int linkedlist_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addlink 1
extern  node * addlink_1();
extern  node * addlink_1_svc();
extern int linkedlist_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_lists (XDR *, lists*);

#else /* K&R C */
extern bool_t xdr_node ();
extern bool_t xdr_lists ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LINKEDLIST_H_RPCGEN */
