/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARRAY_H_RPCGEN
#define _ARRAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Array {
	int a[50];
	int size;
};
typedef struct Array Array;

#define ARRAY_PROG 0x23451111
#define ARRAY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  int * sum_1(Array *, CLIENT *);
extern  int * sum_1_svc(Array *, struct svc_req *);
extern int array_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  int * sum_1();
extern  int * sum_1_svc();
extern int array_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Array (XDR *, Array*);

#else /* K&R C */
extern bool_t xdr_Array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARRAY_H_RPCGEN */
